#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 11 16:37:39 2022

@author: thomas
"""
import numpy as np
import matplotlib.pyplot as plt

liste = [1,2,3,5,6,7,8,9,10,11,14,20,21,22,23,24]
for patient in liste:
    x,y = np.load('/data/thomas/classification epilepsy/chb-mit-scalp-eeg-database-1.0.0/dataset/temporel'+str(patient)+'_x.npy'),np.load('/data/thomas/classification epilepsy/chb-mit-scalp-eeg-database-1.0.0/dataset/temporel'+str(patient)+'_y.npy')[:,0]
    index_1 = np.argwhere(y==1)
    
    index_0 = np.argwhere(y==0)
    
    x_stat_1 = np.sum(np.float32(np.abs(x)),axis = 1)[index_1]/256
    x_stat_0 = np.sum(np.float32(np.abs(x)),axis = 1)[index_0]/256
    
    fig = plt.figure(dpi=300)

    plt.subplot(4,4,1)
    for i in range(16):
        plt.subplot(4,4,i+1)
        plt.violinplot(x_stat_1[:,0,i],showmeans=True,showextrema=False)
        plt.violinplot(x_stat_0[:,0,i],showmeans=True,showextrema=False)
        #plt.yscale('log')
    fig.suptitle(str(patient))
    plt.show()
    